

position_NED_update_frequency = 20.0;   % Hz
velocity_NED_update_frequency = 50.0;   % Hz
attitude_update_frequency = 100.0;      % Hz
body_rates_update_frequency = 200.0;    % Hz


% Position PID gains
PID_gains_position_North = struct( ...
    'kp', 1.0, ...
    'ki', 0.1, ...
    'kd', 0.5);
% Velocity PID gains
PID_gains_velocity_North = struct( ...
    'kp', 1.0, ...
    'ki', 0.0, ...
    'kd', 0.5);






PID_gains_position_East = struct( ...
    'kp',1.25, ...
    'ki', 0.0, ...
    'kd', 0.0);

PID_gains_velocity_East = struct( ...
    'kp', 2.0, ...
    'ki', 0.0, ...
    'kd', 0.0);

PID_gains_velocity_Down = struct( ...
    'kp', 3.0, ...
    'ki', 0.4, ...
    'kd', 0.2);

PID_gains_position_Down = struct( ...
    'kp', 2.0, ...
    'ki', 0.1, ...
    'kd', 0.05);



PID_gains_attitude_pitch = struct( ...
    'kp', 1.0, ...
    'ki', 0.0, ...
    'kd', 0.1);

PID_gains_attitude_yaw = struct( ...
    'kp', 2.0, ...
    'ki', 0.21, ...
    'kd', 0.1)



PID_gains_body_rates_pitch = struct( ...
    'kp', 5.0, ...
    'ki', 0.0, ...
    'kd', 0.0);

PID_gains_body_rates_yaw = struct( ...
    'kp', 10.0, ...
    'ki', 0.05, ...
    'kd', 0.0);



% Attitude PID gains
PID_gains_attitude_roll = struct( ...
    'kp', 4.0, ...
    'ki', 0.0, ...
    'kd', 0.0);


% Body-rate PID gains
PID_gains_body_rates_roll = struct( ...
    'kp', 5.0, ...
    'ki', 0.0, ...
    'kd', 0.0);
