TAKEOFF = struct( ...
    'name', 'TAKEOFF', ...
    'isFlying', true, ...
    'max_vertical_velocity_ms', 0.750, ...
    'max_horizontal_velocity_ms', 0.5, ...
    'max_vertical_acceleration_ms2', 3.0, ...
    'max_horizontal_acceleration_ms2', 2.0, ...
    'max_yaw_velocity_degs', 30.0, ...
    'max_pitch_roll_velocity_degs', 20.0, ...
    'max_yaw_acceleration_degs2', 2500.0, ...
    'max_pitch_roll_acceleration_degs2', 5000.0, ...
    'pitch_roll_abort_angle_deg', 7.0, ...
    'yaw_abort_angle_deg', 15.0, ...
    'min_thrust_percentage', 0.0, ...
    'max_thrust_percentage', 0.0, ...
    'holdTimeMs', 1000, ...
    'epsilon_group', struct( ...
        'epsH', 0.25, ...
        'epsV', 0.05, ...
        'epsYaw', 999));


NAVIGATION = struct( ...
    'name', 'NAVIGATION', ...
    'isFlying', true, ...
    'max_vertical_velocity_ms', 0.2, ...
    'max_horizontal_velocity_ms', 0.1, ...
    'max_vertical_acceleration_ms2', 3.0, ...
    'max_horizontal_acceleration_ms2', 2.0, ...
    'max_yaw_velocity_degs', 20.0, ...
    'max_pitch_roll_velocity_degs', 10.0, ...
    'max_yaw_acceleration_degs2', 40.0, ...
    'max_pitch_roll_acceleration_degs2', 20.0, ...
    'pitch_roll_abort_angle_deg', 15.0, ...
    'yaw_abort_angle_deg', 15.0, ...
    'min_thrust_percentage', 0.0, ...
    'max_thrust_percentage', 0.0, ...
    'holdTimeMs', 1000, ...
    'epsilon_group', struct( ...
        'epsH', 0.25, ...
        'epsV', 0.05, ...
        'epsYaw', 999));


PRE_LANDING = struct( ...
    'name', 'PRE_LANDING', ...
    'isFlying', true, ...
    'max_vertical_velocity_ms', 0.2, ...
    'max_horizontal_velocity_ms', 0.1, ...
    'max_vertical_acceleration_ms2', 3.0, ...
    'max_horizontal_acceleration_ms2', 2.0, ...
    'max_yaw_velocity_degs', 20.0, ...
    'max_pitch_roll_velocity_degs', 10.0, ...
    'max_yaw_acceleration_degs2', 40.0, ...
    'max_pitch_roll_acceleration_degs2', 20.0, ...
    'pitch_roll_abort_angle_deg', 15.0, ...
    'yaw_abort_angle_deg', 15.0, ...
    'min_thrust_percentage', 0.0, ...
    'max_thrust_percentage', 0.0, ...
    'holdTimeMs', 1000, ...
    'epsilon_group', struct( ...
        'epsH', 0.25, ...
        'epsV', 0.07, ...
        'epsYaw', 999));


LANDING = struct( ...
    'name', 'LANDING', ...
    'isFlying', true, ...
    'max_vertical_velocity_ms', 0.3, ...
    'max_horizontal_velocity_ms', 0.1, ...
    'max_vertical_acceleration_ms2', 3.0, ...
    'max_horizontal_acceleration_ms2', 2.0, ...
    'max_yaw_velocity_degs', 20.0, ...
    'max_pitch_roll_velocity_degs', 10.0, ...
    'max_yaw_acceleration_degs2', 40.0, ...
    'max_pitch_roll_acceleration_degs2', 20.0, ...
    'pitch_roll_abort_angle_deg', 15.0, ...
    'yaw_abort_angle_deg', 15.0, ...
    'min_thrust_percentage', 0.0, ...
    'max_thrust_percentage', 0.0, ...
    'holdTimeMs', 1, ...
    'epsilon_group', struct( ...
        'epsH', 0.35, ...
        'epsV', 0.07, ...
        'epsYaw', 999));


